costmap_node:
    ros__parameters:
        costmap:
            resolution: 0.1
            width: 100
            height: 100

            origin:
                position:
                    x: -5.0
                    y: -5.0
                orientation:
                    w: 1.0

            inflation_radius: 1.5
